### ISSUE TITLE
This is Briliant..Bootstrap3?

### ISSUE THREAD

**Issue by gnetsys** [phildionne/golden-bootstrap#1]
Have you stated on bootstrap3? Don't mind contributing...

**Comment by phildionne** [comment]
No, I haven't taken the time to start anything toward supporting bootstrap 3. It would be very nice of you to lay the ground for this though. For what I know of the new grid system, it wouldn't be very hard to implement.

**Comment by phildionne** [comment]
I finally took the time to do it. It's not completely finished though. The responsive part still needs to be handled.
